bangazonworkforcemgt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from hrapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrapp.urls'))
]

hrapp/urls.py
from django.urls import path
from django.conf.urls import include
from hrapp import views
from .views import *

app_name = 'hrapp'
urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),
    path('computers/', computer_list, name='computer_list'),
    path('computers/form', computer_form, name='computer_form'),
    path('computers/<int:computer_id>/', computer_details, name='computer'),
    path('employees/', employee_list, name='employee_list'),
    path('employee/form', employee_form, name='employee_form'),
    path('training_programs/', training_program_list, name='training_programs'),
    path('training_program/form', training_program_form, name='training_program_form'),
    path('training_programs/<int:training_program_id>/', training_program_details, name='training_program_details'),
    path('employees/<int:employee_id>/', employee_details, name='employee'),
    path('training_programs/<int:training_program_id>/form/', training_program_edit_form, name='training_program_edit_form'),
    path('training_programs/<int:training_program_id>/', training_program_details, name='training_program'),
    path('training_programs/<int:training_program_id>/<int:employee_id>/', employee_training_program_details, name='employee_training_program'),
    path('emp_training_programs/<int:employee_id>/form', employee_program_form, name='emp_program_form'),
    path('departments/', department_list, name='department_list'),
    path('departments/form', department_form, name='department_form'),
    path('departments/<int:department_id>', department_details, name='department'),
    path('employees/<int:employee_id>/form/', employee_edit_form, name='employee_edit_form'),
]

hrapp/models/computer.py
from django.db import models
from django.shortcuts import reverse

class Computer(models.Model):
    '''
    description: This class creates a computer and its properties
    properties:
      make: The make will contain the name of the brand of the computer.
      purchase_date: This property contains the purchase date in string form.
      decomission_date: This property contains the decomission date in string form.
      employees: This property contains the many to many relationship with the computer/employee model
    '''

    make = models.CharField(max_length=20)
    purchase_date = models.DateField()
    decommission_date = models.DateField(null=True, blank=True, default=None)
    employees = models.ManyToManyField("Employee", through='EmployeeComputer')

    class Meta:
        verbose_name = ("Computer")
        verbose_name_plural = ("Computers")

    def get_absolute_url(self):
        return reverse("Computer_detail", kwargs={"pk": self.pk})

hrapp/models/departments.py
from django.db import models
from django.shortcuts import reverse

class Department(models.Model):

    dept_name = models.CharField(max_length=50)
    budget = models.FloatField(max_length=50)

    class Meta:
        verbose_name = ("department")
        verbose_name_plural = ("departments")

    def __str__(self):
        return self.dept_name

    def get_absolute_url(self):
        return reverse("Department_detail", kwargs={"pk": self.pk})

hrapp/models/employee.py
from django.db import models
from django.shortcuts import reverse
from .departments import Department

class Employee(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    start_date = models.DateField()
    is_supervisor = models.BooleanField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Employee")
        verbose_name_plural = ("Employees")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("Employee_detail", kwargs={"pk": self.pk})

hrapp/models/employee_computer.py
from django.db import models

class EmployeeComputer(models.Model):
    """
    Creates the join table for the many to many relationship between computers and employees
    """

    employee = models.ForeignKey("Employee", on_delete=models.CASCADE)
    computer = models.ForeignKey("Computer", on_delete=models.CASCADE)
    assign_date = models.DateField(null=True, blank=True, default=None)
    unassign_date = models.DateField(null=True, blank=True, default=None)

hrapp/models/employee_training_program.py
from django.db import models

class Employee_training_program(models.Model):

    """
    Creates the join table for the many to many relationship between training programs and employees
    Author: Ronald Lankford
    """

    employee = models.ForeignKey("Employee", on_delete=models.CASCADE)
    training_program = models.ForeignKey("Training_program", on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("employee_training_program")
        verbose_name_plural = ("employee_training_programs")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("employee_training_program_detail", kwargs={"pk": self.pk})

hrapp/models/training_program.py
from django.db import models

class Training_program(models.Model):

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField()
    max_attendees = models.IntegerField()

    class Meta:
        verbose_name = ("training_program")
        verbose_name_plural = ("training_programs")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("training_program_detail", kwargs={"pk": self.pk})

hrapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {
            "user": request.user
        }

        return render(request, template, context)

hrapp/templates/computers/detail.html
{% extends 'shared/base.html' %}
{% load static %}
  {% block content %}

  <dialog class="infoDialog">
    <div class="infoDialog__message"></div>
    <form action="{% url 'hrapp:computer' computer.id %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="actual_method" value="DELETE">
      <button>Yes, this is my Final Answer</button>
    </form>
    <form action="{% url 'hrapp:computer_list' %}" method="GET">
      {% csrf_token %}
      <button type="submit">Please No!</button>
    </form>
  </dialog>

  <div class="detail_computers">
    <h1>Make / Model: {{ computer.make }}</h1>
    <h2>Purchase Date: {{ computer.purchase_date }}</h2>
    {% if computer.decommission_date != None %}
      <h2>Decommission Date: {{ computer.decommission_date }}</h2>
    {% endif %}
    {% if assigned_computer %}
      <h3>Currently Assigned To: {{ assigned_computer.employee_first }} {{ assigned_computer.employee_last }}</h3>
    {% endif %}
    {% if not assigned_computer %}
      <button id="detail--{{ computer.id }}">Delete</button>
    {% endif %}
  </div>
  {% endblock %}
  

{% block scripts %}
    <script src="{% static 'scripts/computers.js' %}"></script>
{% endblock %}

hrapp/templates/computers/form.html
{% extends 'shared/base.html' %}
  {% block content %}
   <h1>Computer Inventory Form</h1>
    <form action="{% url 'hrapp:computer_form' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="make">Computer Make/Model: </label>
          <input id="make" type="text" name="make">
      </fieldset>
      <fieldset>
          <label for="purchase_date">Purchase Date: </label>
          <input id="purchase_date" type="date" name="purchase_date">
      </fieldset>
      <fieldset>
        <label for="employee">Employee: </label>
        <select id="employee" type="text" name="employee">
          <option value="NULL"></option>
          {% for employee in all_employees %}
            {% if employee.empcomp_id == None %}
              <option value="{{ employee.id }}">{{ employee.first_name }} {{ employee.last_name }}</option>
            {% endif %}
          {% endfor %}
        </select>
      </fieldset>
      <input type="submit" value="Add Computer" />
    </form>
  {% endblock %}

hrapp/templates/computers/list.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />
{% endblock %}

  {% block content %}
    <div class="computer_header">
      <h1>Computers</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'hrapp:computer_form' %}"><button>Add New Computer</button></a>
      {% endif %}
    </div> 
    <ol class="computers">
    {% for computer in all_computers %}
        <li class="computer">
            <a href="{% url 'hrapp:computer' computer.id %}">{{ computer.make }}</a>
        </li>
    {% endfor %}
    </ol>
  {% endblock %}

hrapp/templates/departments/detail.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1>{{ department }}</h1>
    <h2>Employees</h2>
    {% for employee in department.employees %}
        <h4>Name: {{ employee }}</h4>
        <p>Start date: {{ employee.start_date }}</p>
        {% if employee.is_supervisor == 1 %}
        <p>Supervisor: Yes</p>
        {% else %}
        <p>Supervisor: No</p>
        {% endif %}
    {% endfor %}
{% endblock %}

hrapp/templates/departments/form.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1>Create department</h1>
    <form action="{% url 'hrapp:department_list' %}" method="post">
    {% csrf_token %}
        <fieldset>
            <label for="title">Title: </label>
            <input type="text" name="dept_name">
            <br>
            <label for="budget">Budget: </label>
            <input type="text" name="budget">
        </fieldset>
        <input type="submit" value="Create department" />
    </form>
{% endblock %}

hrapp/templates/departments/list.html
{% extends 'shared/base.html'%}

{% block content %}
    <h1>Departments</h1>
    {% if user.is_authenticated %}
    <a href="{% url 'hrapp:department_form' %}"><button>Create department</button></a>
    {% endif %}
    <ul>
    {% for department in departments %}
        <li>
            <h2>
            {% if department.employees.0.first_name %}
            <a href="{% url 'hrapp:department' department.id %}">{{ department.dept_name }}</a>
            {% else %}
            {{ department.dept_name }}
            {% endif %}
            </h2>
            <p>Budget ${{ department.budget }}</p>
            {% if department.employees.0.first_name %}
            <p>Number of employees: {{ department.employees|length }}</p>
            {% else %}
            <p>Number of employees: 0</p>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
        
{% endblock %}

hrapp/templates/employees/detail.html
{% extends 'shared/base.html' %}
{% block content %}
    <h1>{{ employee.first_name }} {{ employee.last_name }}</h1>
    <h2>Department: {{ employee.department.dept_name }}</h2>
    {% if employee.computer.make != None %}
    <p>Computer: {{ employee.computer.make }} </p>
    {% endif %}
    {% if employee.training_programs != None %}
    <h2> Training Programs</h2>
    {% for tp in employee.training_programs %}
    <p>{{ tp.name }} </p>
    {% endfor %}
    {% endif %}
    {% if user.is_authenticated %}
    <button><a href="{% url 'hrapp:emp_program_form' employee.id %}">Assign Employee</a></button>
    {% endif %}

  <form action="{% url 'hrapp:employee' employee.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="actual_method" value="DELETE">
    <button>Delete</button>
  </form>
   <form action="{% url 'hrapp:employee_edit_form' employee.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>

{% endblock %}

hrapp/templates/employees/employees_list.html
{% extends 'shared/base.html' %}

{% block content %}
<h1>Employees</h1>

<ol>
{% for employee in employees %}
    <li>
        <p>{{ employee }}</p>
        Current computer: {{employee.computer}}
    </li>
{% endfor %}
</ol>
{% endblock content %}

hrapp/templates/employees/form.html
{% extends 'shared/base.html' %}
{% block content %}
    {% if employee.id is not None %}
      <form action="{% url 'hrapp:employee' employee.id %}" method="post">
    {% else %}
    <form action="{% url 'hrapp:employee_list' %}" method="post">
    {% endif %}
      {% csrf_token %}
      <fieldset>
          <label for="first_name">First Name: </label>
          <input id="first_name" type="text" name="first_name" value="{{ employee.first_name }}">
      </fieldset>
      <fieldset>
          <label for="last_name">Last Name: </label>
          <input id="last_name" type="text" name="last_name" value="{{ employee.last_name }}">
      </fieldset>
      <fieldset>
          <label for="start_date">Start Date: </label>
          <input id="start_date" type="date" name="start_date" value="{{ employee.start_date }}">
      </fieldset>
       <fieldset>
          <label for="department">Departments: </label>
          <select id="department" type="text" name="department">
                {% for department in all_departments %}
                    <option {% if department.id == employee.department_id %}selected{% endif %} value="{{ department.id }}">
                    {{ department.dept_name }}</option>
                {% endfor %}
          </select>
      </fieldset>
      {% if employee.id is not None %}
       <fieldset>
          <label for="computer_id">Computers: </label>
          <select id="computer_id" type="text" name="computer_id">
            {% for computer in computers %}
            <option value="{{ computer.id }}"> {{ computer.make }} </option>
            {% endfor %}
          </select>
        <fieldset>
      <input type="hidden" name="actual_method" value="PUT" />
      <input type="submit" value="Update" />
      {% else %}
      <input type="submit" value="Add Employee" />
      {% endif %}  
    </form>
{% endblock %}

hrapp/templates/employees/list.html
{% extends 'shared/base.html' %}

{% block content %}
<h1>Employees</h1>

{% if user.is_authenticated %}
<button><a href="{% url 'hrapp:employee_form' %}">Add Employee</a></button>
{% endif %}
<ol>
{% for employee in employees %}
    <li>
        <p><a href="{% url 'hrapp:employee' employee.id %}"> {{ employee }}</a></p>
        Department: {{ employee.department.dept_name}}
    </li>
{% endfor %}
</ol>
{% endblock content %}

hrapp/templates/home.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1 class="header">Welcome to the Bangazon Workforce Management System</h1>
{% endblock content %}

hrapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bangazon Workforce Management</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" type="text/css" media="screen" />
    
</head>

<body>

    
    <nav class="nav">
        <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" class="nav__blob">
            <path fill="#9EF0F0" d="M52.3,-50.8C67.4,-37.2,78.9,-18.6,80.9,2C82.9,22.6,75.3,45.2,60.2,53.2C45.2,61.2,22.6,54.7,1.8,52.9C-19,51.1,-38,54,-44.7,46C-51.4,38,-45.9,19,-48,-2.1C-50.1,-23.3,-59.9,-46.5,-53.2,-60.1C-46.5,-73.6,-23.3,-77.4,-2.3,-75.1C18.6,-72.8,37.2,-64.3,52.3,-50.8Z" transform="translate(100 100)" />
        </svg>
        <a href="/" class="nav__logo"></a>
        <ul class="nav__links">
            <li class="nav__link"><a href="{% url 'hrapp:employee_list' %}">Employees</a></li>
            <li class="nav__link"><a href="{% url 'hrapp:department_list' %}">Departments</a></li>    
            <li class="nav__link"><a href="{% url 'hrapp:computer_list' %}">Computers</a></li>    
            <li class="nav__link"><a href="{% url 'hrapp:training_programs' %}">Training Programs</a></li>   
            {% if not user.is_authenticated %}
            <li class="nav__link--login"><a href="{% url 'hrapp:login' %}">Login</a> 
            {% else %}
            <li class="nav__link nav__link--logout"><a href="{% url 'hrapp:logout' %}">Logout</a></li>    
            {% endif %}
        </ul>
    </nav>
    {% comment %} <hr class="line"> {% endcomment %}
    {% block content %}
    {% endblock %}
    {% block scripts %}
    {% endblock scripts %}

</body>

</html>

hrapp/templates/training_programs/detail.html
{% extends 'shared/base.html' %}

{% load static %}

{% block content %}
  <h1>Training Program</h1>
  <p>Name: {{ training_program.name }}</p>
  <p>Description: {{training_program.description}}</p>
  <p>Start Date: {{training_program.start_date}}</p>
  <p>End Date: {{training_program.end_date}}</p>
  <p>Max Attendees: {{training_program.max_attendees}}</p>

  {% if program_hasnt_started and user.is_authenticated %}
  <section>
    <form action="{% url 'hrapp:training_program' training_program.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="actual_method" value="DELETE-PROGRAM">
        <button>Delete</button>
    </form>
    <form action="{% url 'hrapp:training_program_edit_form' training_program.id %}" method="GET">
        {% csrf_token %}
        <button>Edit</button>
    </form>
  </section>
  {% endif %}

  <h3>Current Employees Attending:</h3>

  {% if not program_employees %}
  <p>Nobody has signed up yet!</p>
  {% endif %}

  {% for employee in program_employees %}
  <div class="employee_training_program">{{employee.first_name}} {{employee.last_name}}
    {% if user.is_authenticated %}
      <form action="{% url 'hrapp:employee_training_program' training_program.id employee.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="actual_method" value="DELETE-EMPLOYEE">
        <button>X</button>
      </form>
    {% endif %}
  </div>
  {% endfor %}

  
{% endblock content %}

hrapp/templates/training_programs/emp_program_form.html
{% extends 'shared/base.html' %}

{% block content %}

{% if training_programs|length == 0 %}
  <h3>No training programs are currently open for enrollment!</h3>
  <p><a href="{% url 'hrapp:employee' employee_id %}"> Go back to details.</a></p>
{% else %}
  <form action="{% url 'hrapp:emp_program_form' employee_id %}" method="post">
    {% csrf_token %}
    <fieldset>
      <label for="training_program">Training Programs: </label>
      <select id="training_program" type="text" name="training_program">
            {% for program in training_programs %}
                <option value="{{ program.id }}">{{ program.name }}</option>
            {% endfor %}
      </select>
      <input type="hidden" name="actual_method" value="ASSIGN_EMPLOYEE">
      <input type="submit" value="Create" />
    </fieldset>
  </form>
{% endif %}

{% endblock content %}

hrapp/templates/training_programs/form.html
{% extends 'shared/base.html' %}

{% block content %}
<h1>Training Program Form</h1>
{% if training_program.id is not None%}
 <form action="{% url 'hrapp:training_program' training_program.id %}" method="post">
{% else %}
 <form action="{% url 'hrapp:training_programs' %}" method="post">
{% endif %}
    {% csrf_token %}
    <fieldset>
        <label for="name">Name: </label>
        <input id="name" type="text" name="name" value="{{training_program.name}}">
    </fieldset>
    <fieldset>
        <label for="description">Description: </label>
        <textarea id="description" type="text" name="description" rows='3' cols='30'>{{training_program.description}}</textarea>
    </fieldset>
    <fieldset>
        <label for="start_date">Start Date: </label>
        <input id="start_date" type="date" name="start_date" value="{{training_program.start_date}}">
    </fieldset>
    <fieldset>
        <label for="end_date">End Date: </label>
        <input id="end_date" type="date" name="end_date" value="{{training_program.end_date}}">
    </fieldset>
    <fieldset>
        <label for="max_attendees">Max Attendees: </label>
        <input id="max_attendees" type="number" name="max_attendees" value="{{training_program.max_attendees}}">
    </fieldset>

    {% if training_program.id is not None %}
        <input type="hidden" name="actual_method" value="PUT">
        <input type="submit" value="Update" />
    {% else %}
        <input type="submit" value="Create" />
    {% endif %}
    </form>
{% endblock content %}

hrapp/templates/training_programs/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <div>
        <h1>Training Programs</h1>
        {% if user.is_authenticated %}
            <a href="{% url 'hrapp:training_program_form' %}"><button>Add Training Program</button></a>
        {% endif %}

        <ol>
        {% for program in all_training_programs %}
            <li>
                <a href="{% url 'hrapp:training_program' program.id%}"> {{ program.name }} </a>
            </li>
        {% endfor %}
        </ol>
    </div>
{% endblock content %}